#!/usr/bin/env bash
#
# Scale test — index big public repos with the release build and record the
# numbers the PRD commits to (§ performance targets):
#
#   * cold full-index wall time   (target: <600s for 10K files w/ Jina v2,
#                                          <180s with the --lite model)
#   * peak RSS during indexing    (target: <700MB for 10K files w/ Jina v2)
#   * warm re-index (no changes)  (expect: near-instant, 0 re-embeds)
#   * incremental re-index        (1 file changed — delete-then-insert path)
#   * index size on disk
#
# Usage:
#
#     ./scripts/scale-test.sh                 # tokio only (sanity rung)
#     ./scripts/scale-test.sh vscode          # the 10K-file PRD-target rung
#     ./scripts/scale-test.sh tokio django vscode
#     ./scripts/scale-test.sh all             # every rung (hours; clones GBs)
#
# Environment:
#
#     BENCH_DIR   workspace for clones/data/reports (default: ~/vektor-bench)
#     LITE=1      use the BAAI/bge-small-en-v1.5 lite model instead of Jina v2
#
# Everything lives under BENCH_DIR — clones in repos/, one shared Vektor
# data_dir in data/ (per-project state is isolated by hashed subdirectory,
# and the ONNX model under data/models/ is downloaded once), and markdown
# reports in reports/. Nothing is written into this repository.

set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT=$(pwd -P)

BENCH_DIR="${BENCH_DIR:-$HOME/vektor-bench}"
DATA_DIR="$BENCH_DIR/data"
CONFIG="$BENCH_DIR/config.toml"
STAMP=$(date +%Y%m%d-%H%M%S)
REPORT="$BENCH_DIR/reports/scale-$STAMP.md"
VEKTOR="$REPO_ROOT/target/release/vektor"

repo_url() {
  case "$1" in
    tokio)      echo "https://github.com/tokio-rs/tokio" ;;        # ~800 Rust files — sanity rung
    django)     echo "https://github.com/django/django" ;;         # ~2.8K Python files — medium rung
    vscode)     echo "https://github.com/microsoft/vscode" ;;      # ~5-9K TS/JS files — PRD-target rung
    grafana)    echo "https://github.com/grafana/grafana" ;;       # Go + TS — multi-language rung
    kubernetes) echo "https://github.com/kubernetes/kubernetes" ;; # ~15K+ Go files — stress rung
    typescript) echo "https://github.com/microsoft/TypeScript" ;;  # 50K-line checker.ts — sub-chunking edge case
    *)          return 1 ;;
  esac
}
ALL_REPOS="tokio django vscode grafana kubernetes typescript"

# --- argument parsing ------------------------------------------------------
REPOS=""
for arg in "${@:-tokio}"; do
  if [ "$arg" = "all" ]; then
    REPOS="$ALL_REPOS"
  elif repo_url "$arg" >/dev/null; then
    REPOS="$REPOS $arg"
  else
    echo "ERROR: unknown repo '$arg' (known: $ALL_REPOS, or 'all')" >&2
    exit 1
  fi
done

# --- preflight ---------------------------------------------------------------
for tool in git protoc shasum; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "ERROR: $tool not found on PATH" >&2
    exit 1
  fi
done

echo "==> cargo build --release (perf numbers from a debug build are fiction)"
cargo build --release

mkdir -p "$BENCH_DIR/repos" "$BENCH_DIR/reports" "$DATA_DIR"

# --- config + model ----------------------------------------------------------
if [ "${LITE:-0}" = "1" ]; then
  MODEL="BAAI/bge-small-en-v1.5"
  DOWNLOAD_ARGS="download --lite"
else
  MODEL="jinaai/jina-embeddings-v2-base-code"
  DOWNLOAD_ARGS="download"
fi

cat > "$CONFIG" <<EOF
# Generated by scripts/scale-test.sh — do not edit; regenerated on every run.
[index]
data_dir = "$DATA_DIR"

[embedding]
backend = "onnx"
onnx_model = "$MODEL"
EOF

SAFE_MODEL=${MODEL//\//--}
if [ ! -f "$DATA_DIR/models/$SAFE_MODEL/onnx/model.onnx" ]; then
  echo "==> downloading ONNX model $MODEL (one-time, shared across repos)"
  # shellcheck disable=SC2086  # DOWNLOAD_ARGS is intentionally word-split
  "$VEKTOR" --config "$CONFIG" models $DOWNLOAD_ARGS
fi

# --- timing helper -----------------------------------------------------------
# macOS /usr/bin/time -l prints peak RSS in BYTES; GNU time -v prints KBYTES.
if /usr/bin/time -l true >/dev/null 2>&1; then
  TIME_FLAG="-l"; RSS_DIVISOR=1048576
else
  TIME_FLAG="-v"; RSS_DIVISOR=1024
fi

WALL_S=""; RSS_MB=""
run_timed() { # run_timed <logfile> <cmd...>; sets WALL_S / RSS_MB
  local log="$1"; shift
  if ! /usr/bin/time "$TIME_FLAG" "$@" >"$log" 2>&1; then
    echo "ERROR: command failed — last 20 log lines ($log):" >&2
    tail -20 "$log" >&2
    return 1
  fi
  WALL_S=$(awk '
    / real .* user / { print $1; exit }                       # macOS
    /Elapsed \(wall clock\)/ {                                 # GNU time
      n = split($NF, t, ":"); s = 0
      for (i = 1; i <= n; i++) s = s * 60 + t[i]
      print s; exit
    }' "$log")
  RSS_MB=$(awk -v div="$RSS_DIVISOR" '
    /[Mm]aximum resident set size/ {
      for (i = 1; i <= NF; i++) if ($i + 0 > 0) { printf "%.0f", $i / div; exit }
    }' "$log")
}

# Fail loudly if an index run reported per-file failures — a "fast" run that
# silently failed to index files must never masquerade as a good result.
assert_no_failures() { # assert_no_failures <logfile>
  local failed
  failed=$(awk -F': ' '/^failed:/ {print $2}' "$1")
  if [ "${failed:-missing}" != "0" ]; then
    echo "ERROR: index run reported failed=${failed:-<stats not found>} (see $1):" >&2
    grep -E '^(files|changed|unchanged|failed|chunks|embeddings|reused|skipped_secrets):' "$1" >&2 || true
    exit 1
  fi
}

# --- report header -----------------------------------------------------------
VEKTOR_SHA=$(git -C "$REPO_ROOT" rev-parse --short HEAD)
DIRTY=""
git -C "$REPO_ROOT" diff --quiet || DIRTY=" (dirty)"
CORES=$(sysctl -n hw.ncpu 2>/dev/null || nproc)
MEM_GB=$(( $(sysctl -n hw.memsize 2>/dev/null || grep -m1 MemTotal /proc/meminfo | awk '{print $2 * 1024}') / 1073741824 ))

cat > "$REPORT" <<EOF
# Vektor scale test — $STAMP

- vektor: \`$VEKTOR_SHA\`$DIRTY (release build)
- model: \`$MODEL\` (backend: onnx)
- machine: $CORES cores, ${MEM_GB}GB RAM, $(uname -sm)
- PRD targets: cold index <600s Jina / <180s lite @ 10K files; RSS <700MB; warm re-index ~0 re-embeds
EOF

# --- per-repo loop -----------------------------------------------------------
for name in $REPOS; do
  url=$(repo_url "$name")
  dir="$BENCH_DIR/repos/$name"

  if [ ! -d "$dir/.git" ]; then
    echo "==> cloning $url (depth 1)"
    git clone --depth 1 "$url" "$dir"
  fi
  sha=$(git -C "$dir" rev-parse --short HEAD)
  total_files=$(git -C "$dir" ls-files | wc -l | tr -d ' ')
  supported_files=$(git -C "$dir" ls-files '*.py' '*.ts' '*.tsx' '*.js' '*.jsx' '*.rs' '*.go' | wc -l | tr -d ' ')

  # Mirror state::project_data_dir — sha256 hex of the canonicalized root —
  # so we can wipe exactly this project's index to force a cold run.
  proj_hash=$(printf '%s' "$(cd "$dir" && pwd -P)" | shasum -a 256 | awk '{print $1}')
  proj_data="$DATA_DIR/$proj_hash"
  rm -rf "$proj_data"

  log_prefix="$BENCH_DIR/reports/$name-$STAMP"

  echo "==> [$name @ $sha] cold index ($supported_files supported / $total_files files)"
  run_timed "$log_prefix-cold.log" "$VEKTOR" --config "$CONFIG" index "$dir"
  assert_no_failures "$log_prefix-cold.log"
  cold_wall=$WALL_S; cold_rss=$RSS_MB

  echo "==> [$name] warm re-index (no changes — expect ~0 re-embeds)"
  run_timed "$log_prefix-warm.log" "$VEKTOR" --config "$CONFIG" index "$dir"
  assert_no_failures "$log_prefix-warm.log"
  warm_wall=$WALL_S

  # Incremental: append a comment to one tracked source file, re-index, revert.
  inc_wall="n/a"
  target_file=$(git -C "$dir" ls-files '*.rs' '*.go' '*.ts' '*.js' '*.py' | head -1)
  if [ -n "$target_file" ]; then
    case "$target_file" in
      *.py) marker="# vektor scale-test marker" ;;
      *)    marker="// vektor scale-test marker" ;;
    esac
    echo "$marker" >> "$dir/$target_file"
    echo "==> [$name] incremental re-index (1 file changed: $target_file)"
    run_timed "$log_prefix-incremental.log" "$VEKTOR" --config "$CONFIG" index "$dir"
    assert_no_failures "$log_prefix-incremental.log"
    inc_wall=$WALL_S
    git -C "$dir" checkout -- "$target_file"
  fi

  if [ -d "$proj_data" ]; then
    index_size=$(du -sh "$proj_data" | awk '{print $1}')
  else
    index_size="unknown (project dir not found under data/ — hash mismatch?)"
  fi

  cat >> "$REPORT" <<EOF

## $name

- source: $url @ \`$sha\` (shallow clone)
- files: $total_files tracked, $supported_files in supported languages
- cold index: ${cold_wall}s wall, ${cold_rss:-?} MB peak RSS
- warm re-index (no changes): ${warm_wall}s
- incremental re-index (1 file): ${inc_wall}s
- index size on disk: $index_size
- logs: \`$log_prefix-{cold,warm,incremental}.log\`
EOF
  echo "==> [$name] done: cold ${cold_wall}s / ${cold_rss:-?}MB RSS, warm ${warm_wall}s, incremental ${inc_wall}s"
done

echo
echo "OK: report written to $REPORT"
echo
cat "$REPORT"
